import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Slider from "../src/components/Slider";
import styles from "../styles/Home.module.css";

export default function Home() {
  // const [res, setRes] = useState({ width: 0, height: 0 });
  const [width, setWidth] = useState(0);

  // const getSize = () => {
  //   return setRes((prev) => {
  //     return {
  //       ...prev,
  //       width: window.innerWidth,
  //       height: window.innerHeight,
  //     };
  //   });
  // };

  useEffect(() => {
    console.log(window.innerWidth, "inner effect");
    window.addEventListener("resize", () =>
      setWidth((prev) => (prev = window.innerWidth))
    );
    return () => {
      window.removeEventListener("resize", () =>
        setWidth((prev) => (prev = window.innerWidth))
      );
    };
  }, []);
  // console.log(window.innerWidth,'inner out');
  console.log(width, "state");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Slider />
    </div>
  );
}
